"""add daily features table

Revision ID: 597dd02a53ab
Revises: 19dbb1f017f2
Create Date: 2026-08-11 01:31:16.098371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "597dd02a53ab"
down_revision: Union[str, Sequence[str], None] = "19dbb1f017f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_features",
        sa.Column("features_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date_id", sa.Integer(), nullable=False),
        sa.Column("steps_7d_avg", sa.Float(), nullable=True),
        sa.Column("steps_28d_avg", sa.Float(), nullable=True),
        sa.Column("hrv_7d_avg", sa.Float(), nullable=True),
        sa.Column("hrv_28d_avg", sa.Float(), nullable=True),
        sa.Column("rhr_7d_avg", sa.Float(), nullable=True),
        sa.Column("sleep_7d_avg", sa.Float(), nullable=True),
        sa.Column("sleep_debt", sa.Float(), nullable=True),
        sa.Column("acute_training_load", sa.Float(), nullable=True),
        sa.Column("chronic_training_load", sa.Float(), nullable=True),
        sa.Column("acute_chronic_ratio", sa.Float(), nullable=True),
        sa.Column("workout_days_7d", sa.Integer(), nullable=False),
        sa.Column("rest_days_7d", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["date_id"],
            ["dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dim_user.user_id"],
        ),
        sa.PrimaryKeyConstraint("features_id"),
        sa.UniqueConstraint("user_id", "date_id", name="uq_features_user_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_features")
    # ### end Alembic commands ###
