"""add daily metrics fact table

Revision ID: 833ac1c44a59
Revises: c5f45ae4cb27
Create Date: 2026-08-09 02:32:21.736582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833ac1c44a59'
down_revision: Union[str, Sequence[str], None] = 'c5f45ae4cb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_daily_metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['dim_device.device_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('user_id', 'date_id', 'device_id', name='uq_daily_metrics_user_date_device')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_daily_metrics')
    # ### end Alembic commands ###
