"""add sleep need to user dimension

Revision ID: 9e65d76d3f5c
Revises: 597dd02a53ab
Create Date: 2026-08-15 23:27:42.409234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e65d76d3f5c'
down_revision: Union[str, Sequence[str], None] = '597dd02a53ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_user', sa.Column('sleep_need_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_user', 'sleep_need_hours')
    # ### end Alembic commands ###
