"""add date dimension

Revision ID: c5f45ae4cb27
Revises: bd7ce7d77ab3
Create Date: 2026-08-08 23:45:55.292300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5f45ae4cb27"
down_revision: Union[str, Sequence[str], None] = "bd7ce7d77ab3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_date",
        sa.Column("date_id", sa.Integer(), nullable=False, autoincrement=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("is_weekend", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("date_id"),
        sa.UniqueConstraint("date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dim_date")
    # ### end Alembic commands ###
