"""add sleep fact table

Revision ID: d65c3c38e46e
Revises: 833ac1c44a59
Create Date: 2026-08-09 15:09:47.252959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d65c3c38e46e"
down_revision: Union[str, Sequence[str], None] = "833ac1c44a59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_sleep",
        sa.Column("sleep_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("sleep_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("deep_minutes", sa.Integer(), nullable=True),
        sa.Column("light_minutes", sa.Integer(), nullable=True),
        sa.Column("rem_minutes", sa.Integer(), nullable=True),
        sa.Column("awake_minutes", sa.Integer(), nullable=True),
        sa.Column("sleep_efficiency", sa.Float(), nullable=True),
        sa.Column("avg_heart_rate", sa.Integer(), nullable=True),
        sa.Column("resting_heart_rate", sa.Integer(), nullable=True),
        sa.Column("hrv", sa.Float(), nullable=True),
        sa.Column("awakenings", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["date_id"],
            ["dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["dim_device.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dim_user.user_id"],
        ),
        sa.PrimaryKeyConstraint("sleep_id"),
        sa.UniqueConstraint(
            "user_id", "device_id", "sleep_start", name="uq_sleep_user_device_start"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_sleep")
    # ### end Alembic commands ###
